config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users

  root to: 'home#index'
  resource :profile
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }

  validates_attachment :avatar, content_type: { content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif'] }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new
  end

  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.profile
  end

  def update
    current_user.profile = Profile.new(profile_params)
    if current_user.profile.save
      @profile = current_user.profile
      render action: 'show', notice: 'Profile update success.'
    else
      render action: 'edit'
    end
  end

  def create
    current_user.profile = Profile.new(profile_params)
    if current_user.profile.save
      @profile = current_user.profile
      render action: 'show', notice: 'Profile register success.'
    else
      render action: 'new'
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:introduction, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/home/index.html.erb
<h1>This is <%= current_user.username %>'s Home</h1>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeleniumSnapshotSample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Sample</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <% if user_signed_in? %>
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if current_page?(root_path) %>">
              <%= link_to "Home", root_path %>
            </li>
            <li class="<%= 'active' if params[:controller] == 'profiles' %>">
              <%= link_to "Profile", profile_path %>
            </li>
          </ul>
          <% end %>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <p class="navbar-text">Logged in as <strong><%= current_user.username %></strong>.</p>
            <li><%= link_to "logout", destroy_user_session_path, method: :delete, id: 'logout' %></li>
            <% else %>
            <li><%= link_to "Signup", new_user_registration_path %></li>
            <li><%= link_to "Signin", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </header>


  <% if alert.present? %>
  <div class="alert alert-danger" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    <%= alert %>
  </div>
  <% end %>

  <% if notice.present? %>
  <div class="alert alert-info" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    <%= notice %>
  </div>
  <% end %>
  <%= yield %>


</body>
</html>

app/views/profiles/_form.erb
<%= form_for(@profile, url: profile_path) do |f| %>
  <div class="field">
    <%= f.label :introduction %><br />
    <%= f.text_area :introduction, size: '100x10' %>
  </div>
  <br />
  <div class="field">
    <%= f.file_field :avatar %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/_form.html.erb
<%= form_for(@profile, url: profile_path) do |f| %>
  <div class="field">
    <%= f.file_field :avatar %>
  </div>
  <br />
  <div class="field">
    <%= f.label :introduction %><br />
    <%= f.text_area :introduction, size: '100x10' %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/_header.html.erb
<h3><p>Name: <%= content_tag(:span, current_user.username, id: 'username')%></p></h3>
<h3><p>Email: <%= content_tag(:span, current_user.email, id: 'email') %></p></h3>

app/views/profiles/edit.html.erb
<%= render 'profiles/header' %>
<br>
<%= render 'profiles/form' %>

app/views/profiles/new.html.erb
<%= render 'profiles/header' %>
<br>
<%= render 'profiles/form' %>

app/views/profiles/show.html.erb
<%= render 'profiles/header' %>

<% if @profile %>
<p><%= image_tag @profile.avatar.url(:medium) %></p>
<% end %>

<% if @profile %>
<h3>Introduction: </h3>
<%= simple_format(@profile.introduction.present? ? @profile.introduction : '未登録') %>
<% end %>

<% unless @profile %>
<p> <%= link_to 'Please register your profile!', new_profile_path %> </p>
<% else %>
<p> <%= link_to 'Edit your profile!', edit_profile_path %> </p>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>